[project]
name = "jdango-batch-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.5.3",
    "django>=5.2.3",
    "django-celery-results>=2.6.0",
    "flower>=2.0.1",
    "redis>=6.2.0",
]
